.TH DOZORD 8 "1 May 2020" "Free Software" "User Manuals"
.SH NAME
dozord \- Astra Dozor Security System protocol daemon
.SH SYNOPSIS
dozord -s <site id> -k <pincode> [\-p 1111] [\-d] [\-h]

.SH DESCRIPTION
dozord is an free implementation of the Astra Dozor Security
System server to collect security events and control Astra 
Dozor Box

.SH "COMMAND-LINE OPTIONS"
.IP -s
Astra Box device ID
.IP -k
Astra Box device pincode
.IP -p
listen specified port, 1111 by default
.IP -d
runs in debug mode, highly verbose (will report
every request and commands performed by the server)
.IP -h
displays help

.SH AUTHORS
dozord was implemented and created by Denis Morozov
<n.halcyon@gmail.com>.